name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com
          rev=$(git rev-parse --short HEAD)
          docker build . -t hello
          docker tag hello 244530008913.dkr.ecr.eu-west-1.amazonaws.com/eilert/repo:$rev
          docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/eilert/repo:$rev
          
  push_to_dockerhub:
    name: Push Docker image to Docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build and push Docker image
        run: |
          git config --global credential.helper "cache --timeout=86400"
          git config --global user.name eilertpeilert
          git config --global user.email eilert-t@hotmail.com
          docker build . -t fantasticapp
          docker login
          docker tag fantasticapp eilertpeilert/fantasticapp
          docker push eilertpeilert/fantasticapp        
          
